- name: Install and Run Jenkins
  hosts: all
  tasks:
   - name: install java
     apt:
      name: openjdk-8-jdk
      state: present
      update_cache: yes
   - name: install jenkins war file
     get_url:
      url: https://get.jenkins.io/war-stable/2.319.2/jenkins.war
      dest: /home/ubuntu/
   - name:
     shell:
      'java -jar jenkins.war'

